name: Run Python Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Exécuter le script Python
      - name: Run script
        run: python scripts/test.py

      # Option 1 : Archiver le fichier généré
      - name: Upload generated file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cleaned-dataset
          path: data/Cleaned_Youtube_Channels_Dataset.csv

      # Option 2 : Ajouter et pousser les changements
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add data/Cleaned_Youtube_Channels_Dataset.csv
          git commit -m "Add cleaned dataset"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
