name: Run Python Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Exécuter les scripts Python
      - name: Run cleaning script
        run: python scripts/test.py

      - name: Run visualization script
        run: python scripts/visuel.py

      # Étape 5 : Archiver les fichiers générés
      - name: Upload generated files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-files
          path: |
            data/Cleaned_Youtube_Channels_Dataset.csv
            data/Top_Countries_Subscribers.pdf

      # Étape 6 : Configurer Git et pousser les changements
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add data/Cleaned_Youtube_Channels_Dataset.csv data/Top_Countries_Subscribers.pdf
          git commit -m "Add cleaned dataset and visualization"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
